trigger:
- master

pool:
  name: 'Default'

steps:
#   - task: downloadertask@0
#     inputs:
#       host: 'cw09.compuware.com'
#       port: '47623'
#       codePage: '1047'
#       windowsTopazWorkbenchCliHome: 'C:\Jalaj\TopazISPW\InstalledApplication\Topaz\TopazWorkbenchCLI'
#       windowsSourceDownloadLocation: 'C:\Jalaj\TopazISPW\AzureTest'
#       containerType: 'Assignment'
#       containerId: 'KATE012376'
#       runtimeConfig: 'tpzp'
#       componentType: 'cob'
#       level: 'dev1'
#       downloadIncludes: 'false'
#       downloadUnchangedSource: 'false'
    
    - task: CmdLine@2
      displayName: Download Mainframe Code
      inputs:
        script: |
          CD $(workspaceRoot)
          echo Downloading Mainframe Code using Parameters
          echo Host IP     : $(host)
          echo Port        : $(port)
          echo Code Page     : $(codePage)
          echo CLI Home    : $(windowsTopazWorkbenchCliHome)
          echo Source Download Location    : $(windowsSourceDownloadLocation)
          echo Runtime Configuration : $(runtimeConfig)
          echo Container Type        : $(containerType)
          echo Container Id   : $(containerId)
          
          $(windowsTopazWorkbenchCliHome)\\SCMDownloaderCLI.bat -host $(host) -port $(port) -id $(id) -pass $(password) -protocol None -code $(codePage) -timeout 0 -targetFolder $(windowsSourceDownloadLocation) -data $(windowsSourceDownloadLocation) -ispwServerConfig $(runtimeConfig) -scm ispwc -ispwContainerName $(containerId) -ispwContainerType $(containerType) -ispwServerLevel dev1 -ispwDownloadAll true